config/routes.rb
Usercommunications::Engine.routes.draw do
  resources :usermaildata
  root to:"usermaildata#index"
end

app/models/usercommunications/application_record.rb
module Usercommunications
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/usercommunications/usermaildatum.rb
module Usercommunications
  class Usermaildatum < ApplicationRecord
    #Usercommunications::Usermaildatum
  end
end

app/controllers/usercommunications/application_controller.rb
module Usercommunications
  class ApplicationController < ActionController::Base
  end
end

app/controllers/usercommunications/usermaildata_controller.rb
require_dependency "usercommunications/application_controller"

module Usercommunications
  class UsermaildataController < ApplicationController
    before_action :set_usermaildatum, only: [:show, :edit, :update, :destroy]

    # GET /usermaildata
    def index
      @usermaildata = Usermaildatum.all
    end

    # GET /usermaildata/1
    def show
    end

    # GET /usermaildata/new
    def new
      @usermaildatum = Usermaildatum.new
    end

    # GET /usermaildata/1/edit
    def edit
    end

    # POST /usermaildata
    def create
      @usermaildatum = Usermaildatum.new(usermaildatum_params)

      if @usermaildatum.save
        redirect_to @usermaildatum, notice: 'Usermaildatum was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /usermaildata/1
    def update
      if @usermaildatum.update(usermaildatum_params)
        redirect_to @usermaildatum, notice: 'Usermaildatum was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /usermaildata/1
    def destroy
      @usermaildatum.destroy
      redirect_to usermaildata_url, notice: 'Usermaildatum was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_usermaildatum
        @usermaildatum = Usermaildatum.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def usermaildatum_params
        params.require(:usermaildatum).permit(:username, :useremail, :content)
      end
  end
end

app/helpers/usercommunications/application_helper.rb
module Usercommunications
  module ApplicationHelper
  end
end

app/helpers/usercommunications/usermaildata_helper.rb
module Usercommunications
  module UsermaildataHelper
  end
end

app/views/layouts/usercommunications/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Usercommunications</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "usercommunications/application", media: "all" %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/usercommunications/usermaildata/_form.html.erb
<%= form_with(model: usermaildatum) do |form| %>
  <% if usermaildatum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usermaildatum.errors.count, "error") %> prohibited this usermaildatum from being saved:</h2>

      <ul>
        <% usermaildatum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :useremail %>
    <%= form.text_field :useremail %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usercommunications/usermaildata/edit.html.erb
<h1>Editing Usermaildatum</h1>

<%= render 'form', usermaildatum: @usermaildatum %>

<%= link_to 'Show', @usermaildatum %> |
<%= link_to 'Back', usermaildata_path %>

app/views/usercommunications/usermaildata/index.html.erb
<p id="notice"><%= notice %></p>

<h3 class=main_head>Usermaildata</h3>

<div class=container_new>
<button class=create_new_button><%= link_to 'New Usermaildatum', new_usermaildatum_path ,{style:'color:#FFFFFF;font-weight:550;'} %></button>
</div>
<br><br>

<table class=main_body>
  <thead>
    <tr>
      <th>Username</th>
      <th>Useremail</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usermaildata.each do |usermaildatum| %>
      <tr>
        <td><%= usermaildatum.username %></td>
        <td><%= usermaildatum.useremail %></td>
        <td><%= usermaildatum.content %></td>
        <td><%= link_to 'Show', usermaildatum ,{style:'color:#FFFFFF;font-weight:550;'}%></td>
        <td><%= link_to 'Edit', edit_usermaildatum_path(usermaildatum) ,{style:'color:rgb(42, 157, 143);'} %></td>
        <td><%= link_to 'Destroy', usermaildatum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<style>
.main_head{
  background-color:rgb(244, 162, 97);
  color:white;
  border-radius:5px;
  margin: 8px 150px;
  text-align:center;
  font-weight:550;
  padding:8px;
}
.main_body{
  background-color:rgb(127, 85, 57);
  color:white;
  border-radius:5px;
  text-align:center;
  font-weight:550;
  width:100%;
  table-layout:fixed;
  word-wrap:break-word;
  margin:10px 10px;
}

.create_new_button{
  background-color:rgb(42, 157, 143);
  color:white;
  border:none;
  border-radius:5px;
  padding:8px;
}

.container_new{
  text-align:center;
  position: absolute;
  left: 45%;
}
th,td{padding:10px;}
</style>

app/views/usercommunications/usermaildata/new.html.erb
<h1>New Usermaildatum</h1>

<%= render 'form', usermaildatum: @usermaildatum %>

<%= link_to 'Back', usermaildata_path %>

app/views/usercommunications/usermaildata/show.html.erb
<body>
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Username:</strong>
    <%= @usermaildatum.username %>
  </p>

  <p>
    <strong>Useremail:</strong>
    <%= @usermaildatum.useremail %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @usermaildatum.content %>
  </p>

  <%= link_to 'Edit', edit_usermaildatum_path(@usermaildatum) %> |
  <%= link_to 'Back', usermaildata_path %>
</body>

<style>

</style>